"""Tests for Theorems 1 and 5 of the thesis.

Theorem 1 (under the unit-vector hypothesis): a matrix preserves angles iff
it is orthogonal.

Theorem 5: the linear maps R² → R² preserving angles are generated by
rotations, reflections, and dilations.
"""

from __future__ import annotations

import math

import numpy as np
import pytest

from pyconformal.linear import Dilation, LinearMap, Reflection, Rotation


# =========================================================================
# Theorem 1: angle preservation ⇔ orthogonal (unit vectors)
# =========================================================================
class TestTheorem1:
    """Theorem 1 of the thesis (§1.2): under unit-vector hypothesis,
    a matrix preserves angles iff it is orthogonal."""

    @pytest.mark.parametrize(
        "M",
        [
            Rotation(0.3),
            Rotation(1.7),
            Reflection(0.0),
            Reflection(0.8),
            Reflection(2.0),
        ],
    )
    def test_orthogonal_preserves_angles(self, M: LinearMap) -> None:
        """Direction ⇒: any orthogonal matrix preserves angles."""
        assert M.is_orthogonal()
        assert M.preserves_angles()

    def test_non_orthogonal_pure_dilation_still_preserves_angles(self) -> None:
        """A dilation with |λ| ≠ 1 is not orthogonal but still preserves
        angles (it is in P, not in O(2)).

        This is why the thesis introduces Theorems 2–5: the full group of
        angle-preserving linear maps is strictly larger than O(2).
        """
        D = Dilation(2.5)
        assert not D.is_orthogonal()
        assert D.preserves_angles()

    def test_non_angle_preserving_matrix(self) -> None:
        """A non-conformal matrix (e.g. a shear) is not orthogonal and does
        not preserve angles. This is the contrapositive of Theorem 1."""
        shear = LinearMap(np.array([[1.0, 1.0], [0.0, 1.0]]))
        assert not shear.is_orthogonal()
        assert not shear.preserves_angles()


# =========================================================================
# Theorem 5: generation by rotation, reflection, dilation
# =========================================================================
class TestTheorem5:
    """Theorem 5 of the thesis: every angle-preserving linear map factors
    as a composition of rotations, reflections, and dilations."""

    def test_scaled_rotation_decomposes(self) -> None:
        """A "scaled rotation" λ·R(θ) = D(λ) ∘ R(θ).

        This is the prototype of the case-6 composition in Theorem 6.
        """
        lam, theta = 2.5, 0.7
        composed = Dilation(lam) @ Rotation(theta)
        # Build the expected matrix directly
        c, s = math.cos(theta), math.sin(theta)
        expected = lam * np.array([[c, -s], [s, c]])
        np.testing.assert_allclose(composed.matrix, expected, atol=1e-12)
        assert composed.preserves_angles()

    def test_scaled_reflection_decomposes(self) -> None:
        """A scaled reflection λ·Ref(θ) = D(λ) ∘ Ref(θ)."""
        lam, theta = 1.7, 0.4
        composed = Dilation(lam) @ Reflection(theta)
        c, s = math.cos(theta), math.sin(theta)
        expected = lam * np.array([[c, s], [s, -c]])
        np.testing.assert_allclose(composed.matrix, expected, atol=1e-12)
        assert composed.preserves_angles()

    def test_all_generators_in_group_p(self) -> None:
        """Every pure generator preserves angles (sanity check on Theorem 5)."""
        elements = [
            Rotation(0.5),
            Rotation(-1.2),
            Reflection(0.0),
            Reflection(1.1),
            Dilation(2.0),
            Dilation(0.3),
            Dilation(-1.5),
        ]
        for elt in elements:
            assert elt.preserves_angles(), f"{elt!r} should preserve angles"

    def test_arbitrary_composition_in_group_p(self) -> None:
        """A long composition stays in P (closure of Theorem 6 ⇒ Theorem 5)."""
        m = Rotation(0.3) @ Reflection(0.7) @ Dilation(2.0) @ Rotation(-1.1) @ Dilation(0.5)
        assert m.preserves_angles()
