"""Group P of angle-preserving linear maps in R² (Chapter 1 of the thesis).

The thesis proves (Theorem 5) that the linear maps R² → R² preserving angles
are generated by rotations, reflections, and dilations, and that together they
form a group P under composition (Theorem 6, seven cases).

Public API
----------

* :class:`LinearMap` — Generic element of group P (matrix form). Returned by
  compositions that do not collapse to a single pure generator.
* :class:`Rotation` — Rotation by an angle θ. Theorem 2.
* :class:`Reflection` — Reflection across a line through the origin. Theorem 3.
* :class:`Dilation` — Uniform scaling by λ in the nonzero reals. Theorem 4.
* :func:`compose` — Functional alias for the ``@`` operator implementing the
  dispatch of Theorem 6.

References
----------
Vega Penagos, C. A. & Olivero Zapata, H. A. (2015).
*Implementación en software de aplicaciones conformes*.
Universidad del Tolima. Chapter 1, Theorems 1–6, Corollary 1.
"""

from __future__ import annotations

from .base import LinearMap
from .composition import compose
from .generators import Dilation, Reflection, Rotation

__all__ = [
    "Dilation",
    "LinearMap",
    "Reflection",
    "Rotation",
    "compose",
]
