"""The three generators of group P: rotation, reflection, dilation (§1.1).

Theorem 5 of the thesis states that the linear maps R² → R² that preserve
angles are generated by these three transformations.
"""

from __future__ import annotations

import math

import numpy as np

from .base import ArrayF, LinearMap


class Rotation(LinearMap):
    r"""Rotation of the plane by an angle θ around the origin.

    The matrix representation is, following §1.1 of the thesis,

    .. math::

        R(\theta) = \begin{pmatrix}
            \cos\theta & -\sin\theta \\
            \sin\theta & \cos\theta
        \end{pmatrix}.

    Parameters
    ----------
    theta : float
        Rotation angle in radians. Counter-clockwise is positive.

    Notes
    -----
    Rotations form a subgroup of group P (Corollary 1 of the thesis). They
    preserve angles, distances, and orientation: ``det = 1`` and the matrix
    is orthogonal.

    References
    ----------
    Vega Penagos & Olivero Zapata (2015), §1.1 (definition), Theorem 2
    (preservation of angles), Corollary 1 (subgroup).
    """

    __slots__ = ("theta",)

    def __init__(self, theta: float) -> None:
        self.theta: float = float(theta)
        c = math.cos(self.theta)
        s = math.sin(self.theta)
        matrix: ArrayF = np.array([[c, -s], [s, c]], dtype=np.float64)
        super().__init__(matrix)

    def inverse(self) -> Rotation:
        """Return ``Rotation(-θ)``; rotation by ``-θ`` undoes rotation by ``θ``."""
        return Rotation(-self.theta)

    def __repr__(self) -> str:
        """Return a developer-facing debug string."""
        return f"Rotation(theta={self.theta!r})"


class Reflection(LinearMap):
    r"""Reflection of the plane across a line through the origin.

    The matrix representation is, following §1.1 of the thesis,

    .. math::

        \mathrm{Ref}(\theta) = \begin{pmatrix}
            \cos\theta & \sin\theta \\
            \sin\theta & -\cos\theta
        \end{pmatrix}.

    Geometrically, this reflects across the line through the origin that
    makes an angle ``θ/2`` with the positive x-axis.

    Parameters
    ----------
    theta : float
        Reflection-axis parameter in radians.

    Notes
    -----
    Reflections are orthogonal (``det = -1``) and invert orientation.
    A reflection is its own inverse: ``Ref(θ) ∘ Ref(θ) = I``.

    References
    ----------
    Vega Penagos & Olivero Zapata (2015), §1.1 (definition), Theorem 3.
    """

    __slots__ = ("theta",)

    def __init__(self, theta: float) -> None:
        self.theta: float = float(theta)
        c = math.cos(self.theta)
        s = math.sin(self.theta)
        matrix: ArrayF = np.array([[c, s], [s, -c]], dtype=np.float64)
        super().__init__(matrix)

    def inverse(self) -> Reflection:
        """Return ``Reflection(theta)``; a reflection is its own inverse."""
        return Reflection(self.theta)

    def __repr__(self) -> str:
        """Return a developer-facing debug string."""
        return f"Reflection(theta={self.theta!r})"


class Dilation(LinearMap):
    r"""Uniform dilation of the plane by a nonzero real factor ``λ``.

    The matrix representation is, following §1.1 of the thesis,

    .. math::

        D(\lambda) = \begin{pmatrix}
            \lambda & 0 \\
            0 & \lambda
        \end{pmatrix},
        \qquad \lambda \in \mathbb{R} \setminus \{0\}.

    Parameters
    ----------
    lambda_ : float
        Scaling factor. Must be nonzero. Negative values are allowed and
        correspond geometrically to a rotation by π composed with a positive
        dilation.

    Notes
    -----
    Dilations preserve angles but not distances (Theorem 4). They form a
    subgroup of group P (Corollary 1). ``det = λ² > 0``, so dilations
    preserve orientation regardless of the sign of ``λ``.

    Raises
    ------
    ValueError
        If ``lambda_ == 0``.

    References
    ----------
    Vega Penagos & Olivero Zapata (2015), §1.1 (definition), Theorem 4,
    Corollary 1.
    """

    __slots__ = ("lambda_",)

    def __init__(self, lambda_: float) -> None:
        if lambda_ == 0:
            raise ValueError(
                "Dilation factor must be nonzero (see §1.1 of the thesis: λ ∈ R \\ {0})."
            )
        self.lambda_: float = float(lambda_)
        matrix: ArrayF = np.array(
            [[self.lambda_, 0.0], [0.0, self.lambda_]],
            dtype=np.float64,
        )
        super().__init__(matrix)

    def inverse(self) -> Dilation:
        """Return ``Dilation(1/λ)``."""
        return Dilation(1.0 / self.lambda_)

    def __repr__(self) -> str:
        """Return a developer-facing debug string."""
        return f"Dilation(lambda_={self.lambda_!r})"
